spring:
  cloud:
    gateway:
      routes:
        -id : r1
        uri: http://localhost:8081
        predicates:
          - Path= /**
  application:
    name: gateway-service
    discovery:
      enabled: false
server:
  port: 8080

