

spring:
  cloud:
    gateway:
      routes:
        - id : r1
          uri: http://ontological-discovery-service:8081
          predicates:
            - Path= /**
  application:
    name: gateway-service
server:
  port: 8080

