server:
  port: 8080

spring:
  cloud:
    discovery:
      enabled: true
    gateway:
  application:
    name: gateway-service

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka
