version: '3.3'
services:
  # messaging queueu
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      retries: 10


  # Business logic
  product-service:
    container_name: product-service
    image: product-service
    ports:
      - "9090:9090"
    depends_on:
      rabbitmq:
        condition: service_healthy

  customer-service:
    container_name: customer-service
    image: customer-service
    ports:
      - "9091:9091"
    depends_on:
      rabbitmq:
        condition: service_healthy

  order-service:
    container_name: order-service
    image: order-service
    ports:
      - "9092:9092"
    depends_on:
      rabbitmq:
        condition: service_healthy

  # Ontology
  ontological-discovery-service:
    container_name: ontological-discovery-service
    image: ontological-discovery-service
    ports:
    - "8081:8081"
    depends_on:
      product-service:
        condition: service_started
      customer-service:
        condition: service_started
      order-service:
        condition: service_started

  # Gateways
  inner-gateway-service:
    container_name: inner-gateway-service
    image: inner-gateway-service
    ports:
      - "8082:8082"
    depends_on:
      product-service:
        condition: service_started
      customer-service:
        condition: service_started
      order-service:
        condition: service_started
  gateway-service:
    container_name: gateway-service
    image: gateway-service
    ports:
      - "8080:8080"
    depends_on:
      ontological-discovery-service:
        condition: service_started
