server:
  port: 9090


rdf:
  product:
    base-uri: http://www.datadrivenmicroservices.com/pfa/ontology/Product
    file-path: product.rdf

spring:
  rabbitmq:
    host: rabbitmq
  application:
    name: product-service

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka
