server:
  port: 9091

rdf:
  customer:
    base-uri: http://www.datadrivenmicroservices.com/pfa/ontology/customer
    file-path: customer.rdf
spring:
  rabbitmq:
    host: rabbitmq
  cloud:
    discovery:
      enabled: true
  application:
    name: customer-service
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka
