server:
  port: 9092


rdf:
  order:
    base-uri: http://www.datadrivenmicroservices.com/pfa/ontology/order
    file-path: order.rdf
  product:
    base-uri: http://www.datadrivenmicroservices.com/pfa/ontology/product
  customer:
    base-uri: http://www.datadrivenmicroservices.com/pfa/ontology/customer
spring:
  jpa:
    show-sql: true
  rabbitmq:
    host: rabbitmq
  application:
    name: order-service
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka
