server:
  port: 8081


rdf:
  product:
    file-path: product.rdf
  customer:
    file-path: customer.rdf
  order:
    file-path: order.rdf

route-matcher:
  base-url: http://inner-gateway-service:8082
  services:
    product:
      method:
        GET:
          - /product/get
          - /product/get/{productId}
        POST:
          - /product/save
        PUT:
          - /product/update/{productId}
        DELETE:
          - /product/delete/{productId}
    customer:
      method:
        GET:
          - /customer/get
          - /customer/get/{customerId}
        POST:
          - /customer/save
        PUT:
          - /customer/update/{customerId}
        DELETE:
          - /customer/delete/{customerId}
    order:
      method:
        GET:
          - /order/get
          - /order/get/{orderId}
          - /order/get/customer/{customerId}
        POST:
          - /order/create
        PUT:
          - /order/update/{orderId}
        DELETE:
          - /order/delete/{orderId}
spring:
  rabbitmq:
    host: rabbitmq