server:
  port: 8081

route-matcher:
  base-url: http://localhost:8082
  services:
    product:
      method:
        GET:
          - /product/get
          - /product/get/{productId}
        POST:
          - /product/save
        PUT:
          - /product/update
        DELETE:
          - /product/delete/{productId}
    customer:
      method:
        GET:
          - /customer/get
          - /customer/get/{customerId}
        POST:
          - /customer/save
        PUT:
          - /customer/update
        DELETE:
          - /customer/delete/{customerId}
    order:
      method:
        GET:
          - /order/get
          - /order/get/{orderId}
          - /order/get/customer/{customerId}
        POST:
          - /order/create
        PUT:
          - /order/update
        DELETE:
          - /order/delete/{orderId}