server:
  port: 8081


rdf:
  product:
    file-path: product.rdf
  customer:
    file-path: customer.rdf
  order:
    file-path: order.rdf

route-matcher:
  base-url: lb://inner-gateway-service
  services:
    product:
      service-name: PRODUCT-SERVICE
      method:
        GET:
          - /product/get
          - /product/get/{productId}
        POST:
          - /product/save
        PUT:
          - /product/update/{productId}
        DELETE:
          - /product/delete/{productId}
    customer:
      service-name: CUSTOMER-SERVICE
      method:
        GET:
          - /customer/get
          - /customer/get/{customerId}
        POST:
          - /customer/save
        PUT:
          - /customer/update/{customerId}
        DELETE:
          - /customer/delete/{customerId}
    order:
      service-name: ORDER-SERVICE
      method:
        GET:
          - /order/get
          - /order/get/{orderId}
          - /order/get/customer/{customerId}
        POST:
          - /order/create
        PUT:
          - /order/update/{orderId}
        DELETE:
          - /order/delete/{orderId}
spring:
  rabbitmq:
    host: rabbitmq
  application:
    name: ontological-discovery-service

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka
